wandb_version: 1

batch_size:
  desc: null
  value: 2
betas:
  desc: null
  value:
  - 0.9
  - 0.95
clip_gradients:
  desc: null
  value: false
epochs:
  desc: null
  value: 3
grad_norm_clip:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.0001
lstm:
  desc: null
  value: true
num_workers:
  desc: null
  value: 0
viterbi_algorithm:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.11
    framework: huggingface
    huggingface_version: 4.28.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1695877205.220961
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 33
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 33
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      3:
      - 1
      - 16
      - 23
      4: 3.10.12
      5: 0.15.11
      6: 4.28.0
      8:
      - 1
      - 5
      - 12
      13: linux-x86_64
